USE taxi_app1;

ALTER TABLE chauffeur
  ADD COLUMN IF NOT EXISTS driver_lat DOUBLE NULL,
  ADD COLUMN IF NOT EXISTS driver_lng DOUBLE NULL,
  ADD COLUMN IF NOT EXISTS update_position_driver TIMESTAMP NULL DEFAULT NULL;
